// <auto-generated />
namespace eQuiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MacAddress_IpAddress_Uniqueness_Removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MacAddress_IpAddress_Uniqueness_Removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201507131356421_MacAddress_IpAddress_Uniqueness_Removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
