// <auto-generated />
namespace eQuiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rename_LoginTime_Field_to_LoginTimeUtc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_LoginTime_Field_to_LoginTimeUtc));
        
        string IMigrationMetadata.Id
        {
            get { return "201605081150199_Rename_LoginTime_Field_to_LoginTimeUtc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
